version: '3.8'
services:
  postgres_brief:
    image: postgres:15
    container_name: postgres_brief
    networks:
      - simplon-local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zythologue_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init_db:/docker-entrypoint-initdb.d

volumes:
  postgres_data:

networks:
  simplon-local:
    driver: bridge
